Reducing support channels
splunk/docker-splunk pull request #37
Opened 2018-10-11 16:20 UTC by nwang92

2018-10-11 16:29 UTC, amitmookerjee requested changes
Add the link to the docker room - https://splunk-usergroups.slack.com/messages/C1RH09ERM/ .
Also add the following blurb from support

> If you are a Splunk Enterprise customer with a valid support entitlement contract, and have a Splunk related question you can also open a support case on the https://www.splunk.com/ support portal.
> For details on the supported architectures, please refer to the documentation http://docs.splunk.com/Documentation/Splunk/latest/Installation/Systemrequirements#Containerized_computing_platforms

2018-10-12 17:14 UTC, nwang92 commented
@amitmookerjee done

2018-10-12 17:46 UTC, arctan5x approved these changes

2018-10-12 19:59 UTC, amitmookerjee approved these changes

2018-10-15 17:40 UTC, merged